num_classes: 2
channel: 'A'
num_epochs: 25
learning_rate: 0.00001
train_CNN: True
batch_size: 32
shuffle: True
pin_memory: True
num_workers: 8
transform_resize: [256, 256]
transform_crop: [224, 224]
transform_normalize_mean: [0.5, 0.5, 0.5]
transform_normalize_var: [0.5, 0.5, 0.5]
listofNetwork:
  'vit_b_16': 'models.vit_b_16()'
