num_classes: 2
channel: ['bs_f200_A','bs_f200_P','bs_f300_A','bs_f300_P','bs_f400_A','bs_f400_P',
        'nc_f200_A','nc_f200_P','nc_f300_A','nc_f300_P','nc_f400_A','nc_f400_P',
        'pr_025_A','pr_025_P','pr_075_A','pr_075_P','pr_100_A','pr_100_P',
        'pr_125_A','pr_125_P','pr_150_A','pr_150_P','pr_175_A','pr_175_P']
#channel : ['bs_f300_A','bs_f300_P' ]
num_epochs: 25
learning_rate: 0.00001
train_CNN: True
batch_size: 4
shuffle: True
pin_memory: True
num_workers: 8
transform_resize: [256, 256]
transform_crop: [224, 224]
transform_normalize_mean: [0.5]
transform_normalize_var: [0.5]
listofNetwork:
  'VideoSwin': 'models.alexnet()'
