num_classes: 2
channel : ['SSSRES_1','SSSRES_2','SSSRES_3','SSSRES_4','SSSRES_5','SSSRES_6','SSSRES_7','SSSRES_8','SSSRES_9','SSSRES_10','SSSRES_11','SSSRES_12',
'SSSRES_13','SSSRES_14','SSSRES_15','SSSRES_16','SSSRES_17','SSSRES_18','SSSRES_19','SSSRES_20','SSSRES_21','SSSRES_22','SSSRES_23','SSSRES_24' ]
num_epochs: 25
learning_rate: 0.00001
train_CNN: True
batch_size: 2
shuffle: True
pin_memory: True
num_workers: 8
transform_resize: [256, 256]
transform_crop: [224, 224]
transform_normalize_mean: [0.5]
transform_normalize_var: [0.5]
listofNetwork:
  'TimeSformer': 'models.alexnet()'
